plugins:
  x_chat_customisations_enabled:
    default: true
    client: false
  x_chat_customisations_enhanced_logging:
    default: false
    client: false
  x_chat_customisations_chat_summary_emails_enabled:
    default: true
    client: false
  x_chat_customisations_channel_creation_default_category_id:
    type: category
    client: true
    default: 4
  x_chat_customisations_private_chat_dummy_category_id:
    type: category
    client: true
    default: 4
